name: CI

on:
  push:
    branches:
    - main
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  integration:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Start containers
      run: npm run container:test:integration

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:integration

    - name: Stop containers
      if: always()
      run: npm run container:test:integration:stop