name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  continuous-integration-checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v1

    - name: Setup - Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: Setup - Install dependencies
      run: npm install
    
    - name: Lint
      run: npm run lint

    - name: Typescript build check
      run: npm run build

    - name: Start API and DB containers
      run: npm run container:test:integration

    - name: Run tests
      run: npm run test:integration

    - name: Stop containers
      if: always()
      run: npm run container:test:integration:stop
